export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'

export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT'
export const CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR'

export const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS'
export const CLEAR_INGREDIENT_DETAILS = 'CLEAR_INGREDIENT_DETAILS'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED'
